title: Welcome to Jake Price's homepage!
description: Feel free to bookmark this page to keep an eye on my project updates, publications, and (perhaps most importantly) my homebrewing. 
author: jake price
email: jacob.r.price@drexel.edu
twitter: Jake_in_the_Lab
github_username: JacobRPrice

markdown: kramdown
theme: minima
