title: J. R. Price
#description: Feel free to bookmark this page to keep an eye on my project updates, publications, and (perhaps most importantly) my homebrewing. 
author: Jacob R Price
email: jacob.r.price@drexel.edu
twitter_username: Jake_in_the_Lab
github_username: JacobRPrice


# designate pages (in order) to show in header
header_pages:
 - 9-about.md


# build settings
markdown: kramdown
theme: minima

# More fields are available. refer to:
# https://github.com/jekyll/minima/blob/master/_config.yml
# https://github.com/barryclark/jekyll-now/blob/master/_config.yml
