title: J. R. Price
author: Jacob R Price
email: jacob.r.price@drexel.edu
twitter_username: Jake_in_the_Lab
github_username: JacobRPrice
description: #> # this means to ignore newlines until "baseurl:"
  Environmental engineering, micro- and molecular biology, Penn State football, and beer.  
  -  
  Not necessarily in that order.


# designate pages (in order) to show in header
header_pages:
 - 1-research.md
 - 2-publications.md
 - 3-teaching.md
# - 4-R.md
 - 5-brewing.md
 - 9-about.md

plugins:
  - jekyll-seo-tag

# build settings
markdown: kramdown
theme: minima
highlighter: rouge

# More fields are available. refer to:
# https://github.com/jekyll/minima/blob/master/_config.yml
# https://github.com/barryclark/jekyll-now/blob/master/_config.yml
