theme: jekyll-theme-slate
title: Welcome to Jake Price's homepage!
description: Feel free to bookmark this page to keep an eye on my project updates, publications, and (perhaps most importantly) my homebrewing. 
navbar:
 title: "jacobrprice"
 type: inverse
 left:
  - text: "research"
  - text: "publications"
