title: J. R. Price
#description: Feel free to bookmark this page to keep an eye on my project updates, publications, and (perhaps most importantly) my homebrewing. 
author: Jacob R Price
email: jacob.r.price@drexel.edu
twitter: Jake_in_the_Lab
github_username: JacobRPrice

markdown: kramdown
theme: minima
